name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
    strategy:
      matrix:
        python-version:
          - '3.8.x'
          - '3.9.x'
          - '3.10.x'
          - '3.11.x'
          - '3.12.x'

    name: Python ${{ matrix.python-version }} test on ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run tests
        run: |
          pytest
